const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
const POSTS_REQUEST_ERROR = 'POSTS_REQUEST_ERROR';
const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
const WRITE_COMMENT = 'WRITE_COMMENT';
const CREATE_COMMENT = 'CREATE_COMMENT';



export {
  FETCH_POSTS_REQUEST,
  FETCH_POSTS_SUCCESS,
  POSTS_REQUEST_ERROR,
  FETCH_POST_SUCCESS,
  WRITE_COMMENT,
  CREATE_COMMENT
};
